data gathering - csv file formate , Json/sql ,
Fetch API , WEB scraping( these cover in next four viedos)

Today lean about csv files

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/content/cs2_all_tiers_games.csv")
df

,Unnamed: 0,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
0,0,7299109,153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,4.0,98.6,77.3,12.0,14.0,18.0,8.0,64.5,68.2,-4.0
1,1,7299109,153294.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,2.0,67.2,72.7,6.0,13.0,16.0,8.0,76.8,72.7,-3.0
2,2,7299109,-153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,6.0,82.9,75.0,18.0,27.0,34.0,16.0,70.7,70.5,-7.0
3,3,7299050,153284.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,1.0,69.5,73.9,7.0,9.0,11.0,4.0,57.0,73.9,-2.0
4,4,7299050,153289.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,3.0,63.6,78.9,-1.0,10.0,13.0,4.0,66.2,68.4,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19026,1009,10064202,NaN,Buster CS2 League,233027,GUN5,233028,Forward Gaming,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19027,1010,10064200,NaN,Buster CS2 League,233023,HUEC,233024,FatherSAndSons,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19028,1011,10064199,NaN,Buster CS2 League,233021,Insilio,233022,Forward Gaming,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19029,1012,10064198,NaN,Buster CS2 League,233019,GUN5,233020,CYBERSHOKE Esports,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19030,1013,10064201,NaN,Buster CS2 League,233025,ARCRED,233026,Nemiga Gaming,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. opening a csv file from an url

In [5]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/plotly/datasets/refs/heads/master/data.csv"
headers = {"User-Agent": "Monilla/5.0 (macintosh; Intel Mac OS x 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url,headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149995,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

4. SET PARAMETER
like wothout use an sep = '\t' occuring an problem like merged show
or name will provide using list

In [12]:
pd.read_csv("/content/movie_titles_metadata.tsv", sep='\t', names = ['sno','name','relase_year','rating','votes','genres'])

,sno,name,relase_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

6. HEADER PARARMETER - USE WHEN LIKE YOUE COLOMN NAME SHOW AS YOUR ROW NAME ( here is this type of dtat set is not avaivble so error may got)

In [8]:
pd.read_csv("/content/cs2_all_tiers_games.csv")
#header=1 sahi karrne kke liye

,Unnamed: 0,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
0,0,7299109,153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,4.0,98.6,77.3,12.0,14.0,18.0,8.0,64.5,68.2,-4.0
1,1,7299109,153294.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,2.0,67.2,72.7,6.0,13.0,16.0,8.0,76.8,72.7,-3.0
2,2,7299109,-153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,6.0,82.9,75.0,18.0,27.0,34.0,16.0,70.7,70.5,-7.0
3,3,7299050,153284.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,1.0,69.5,73.9,7.0,9.0,11.0,4.0,57.0,73.9,-2.0
4,4,7299050,153289.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,3.0,63.6,78.9,-1.0,10.0,13.0,4.0,66.2,68.4,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19026,1009,10064202,NaN,Buster CS2 League,233027,GUN5,233028,Forward Gaming,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19027,1010,10064200,NaN,Buster CS2 League,233023,HUEC,233024,FatherSAndSons,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19028,1011,10064199,NaN,Buster CS2 League,233021,Insilio,233022,Forward Gaming,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19029,1012,10064198,NaN,Buster CS2 League,233019,GUN5,233020,CYBERSHOKE Esports,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19030,1013,10064201,NaN,Buster CS2 League,233025,ARCRED,233026,Nemiga Gaming,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

7. USE_COL paramter -  means data insert karte hai to kuch colomn he chiaye pate hai ya kuch unnnesary hote hai

In [7]:
pd.read_csv("/content/cs2_all_tiers_games.csv",usecols=['match_id','game_id' , 'tournament'])

       match_id   game_id                                  tournament
0       7299109  153292.0  PGL Astana 2026. Closed European Qualifier
1       7299109  153294.0  PGL Astana 2026. Closed European Qualifier
2       7299109 -153292.0  PGL Astana 2026. Closed European Qualifier
3       7299050  153284.0  PGL Astana 2026. Closed European Qualifier
4       7299050  153289.0  PGL Astana 2026. Closed European Qualifier
...         ...       ...                                         ...
19026  10064202       NaN                           Buster CS2 League
19027  10064200       NaN                           Buster CS2 League
19028  10064199       NaN                           Buster CS2 League
19029  10064198       NaN                           Buster CS2 League
19030  10064201       NaN                           Buster CS2 League

[19031 rows x 3 columns]

8. squeeze parameter - means only one colomn are need
squeeze = ture ( aab yh data frame na bnkar ke pandas series ban jata hai)

In [9]:
pd.read_csv("/content/cs2_all_tiers_games.csv", usecols=['match_id'] )

       match_id
0       7299109
1       7299109
2       7299109
3       7299050
4       7299050
...         ...
19026  10064202
19027  10064200
19028  10064199
19029  10064198
19030  10064201

[19031 rows x 1 columns]

9. SKIPROES/NROWS PARARMETER
nrow = 100 ( means apko jitni need hai utna usae kar skate hai_)

In [10]:
# pd.read_csv("/content/cs2_all_tiers_games.csv" , skiprows=[0,1])
pd.read_csv("/content/cs2_all_tiers_games.csv" , nrows=100)

,Unnamed: 0,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
0,0,7299109,153292,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,4.0,98.6,77.3,12.0,14.0,18.0,8.0,64.5,68.2,-4.0
1,1,7299109,153294,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,2.0,67.2,72.7,6.0,13.0,16.0,8.0,76.8,72.7,-3.0
2,2,7299109,-153292,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,6.0,82.9,75.0,18.0,27.0,34.0,16.0,70.7,70.5,-7.0
3,3,7299050,153284,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,1.0,69.5,73.9,7.0,9.0,11.0,4.0,57.0,73.9,-2.0
4,4,7299050,153289,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,3.0,63.6,78.9,-1.0,10.0,13.0,4.0,66.2,68.4,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,7048401,125786,BLAST Open Spring 2026,288478,9z Team,288479,MOUZ,2.0,1.0,...,4.0,57.5,68.2,-8.0,11.0,17.0,4.0,63.7,63.6,-6.0
96,96,7048401,-125784,BLAST Open Spring 2026,288478,9z Team,288479,MOUZ,2.0,1.0,...,18.0,56.6,65.8,-16.0,43.0,48.0,17.0,77.6,62.9,-5.0
97,97,7042616,125782,BLAST Open Spring 2026,288480,Team Liquid,288481,Ninjas in Pyjamas,2.0,1.0,...,7.0,75.4,61.1,-2.0,29.0,27.0,14.0,97.8,72.2,2.0
98,98,7042616,125783,BLAST Open Spring 2026,288480,Team Liquid,288481,Ninjas in Pyjamas,2.0,1.0,...,3.0,68.3,63.6,1.0,15.0,19.0,5.0,91.4,72.7,-4.0
99,99,7042616,125781,BLAST Open Spring 2026,288480,Team Liquid,288481,Ninjas in Pyjamas,2.0,1.0,...,3.0,73.3,75.0,3.0,15.0,9.0,4.0,91.1,68.8,6.0

12. DTYPE PARARMETER

In [17]:
pd.read_csv('/content/cs2_all_tiers_games.csv',dtype={'score2_match': int})

/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py:234: RuntimeWarning: invalid value encountered in cast
  chunks = self._reader.read_low_memory(nrows)

ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 9

13. HANDLING DATES